package: hello
version: '0.1.6alpha'
title: 'translate:title'
author: 'Pixelfirma, alexplus_de, pixeldaniel'
supportpage: 'https://github.com/alexplusde/hello/'
icon: fa-smile-o

requires:
    redaxo: ^5.6.0
    packages:
        cronjob: '^2.0'
page:
    title: 'translate:title'
    pjax: false
    icon: rex-icon fa-smile-o
    perm: admin

pages:
    system/hello:
        title: 'translate:title'
        pjax: false
        icon: rex-icon fa-smile-o
    hello/docs:
        title: 'translate:hello_docs'
        pjax: false
        icon: rex-icon fa-smile-o
        itemclass: pull-right 