package: hello
version: '0.4.2alpha'
title: 'translate:title'
author: 'Pixelfirma, alexplus_de, pixeldaniel'
supportpage: 'https://github.com/alexplusde/hello/'
icon: fa-smile-o

requires:
    redaxo: ^5.4.0
    packages:
        cronjob: '^2.0'
page:
    title: 'translate:title'
    pjax: false
    icon: rex-icon
    perm: admin

pages:
    system/hello:
        title: 'translate:hello_title'
        pjax: false
    hello/docs:
        title: 'translate:hello_docs'
        pjax: false
        itemclass: pull-right 